export const adventureCollections = [
  {
    id: 1,
    title: "Canoe Boating",
    price: "110.00",
    rating: 5,
    image: "/images/experiences/boating.webp",
  },
  {
    id: 2,
    title: "Camping",
    price: "210.00",
    rating: 5,
    image: "/images/experiences/camping.webp",
  },
  {
    id: 3,
    title: "Bamboo Rafting",
    price: "158.00",
    rating: 5,
    image: "/images/experiences/bamboo_rafting.webp",
  },
  {
    id: 4,
    title: "Canyon Rope Swing",
    price: "180.00",
    rating: 5,
    image: "/images/experiences/rope_swing.webp",
  },
  {
    id: 5,
    title: "Freestyle Canyoning",
    price: "180.00",
    rating: 5,
    image: "/images/experiences/canyoning.webp",
  },
  {
    id: 6,
    title: "Hiking",
    price: "165.00",
    rating: 5,
    image: "/images/experiences/hiking.webp",
  },
  {
    id: 7,
    title: "Hills Climbing",
    price: "105.00",
    rating: 5,
    image: "/images/experiences/hills_climbing.webp",
  },
  {
    id: 8,
    title: "Horse Riding",
    price: "180.00",
    rating: 5,
    image: "/images/experiences/horse_riding.webp",
  },
  {
    id: 9,
    title: "Horseback Riding",
    price: "205.00",
    rating: 5,
    image: "/images/experiences/horseback_riding.webp",
  },
  {
    id: 10,
    title: "Kayaking",
    price: "140.00",
    rating: 5,
    image: "/images/experiences/kayaking.webp",
  },
  {
    id: 11,
    title: "Mountain Climbing",
    price: "180.00",
    rating: 5,
    image: "/images/experiences/climbing.webp",
  },
  {
    id: 12,
    title: "Mountain Cycling",
    price: "180.00",
    rating: 5,
    image: "/images/experiences/cycling.webp",
  },
];
